DROP TABLE IF EXISTS EMP_1;
CREATE TABLE IF NOT EXISTS EMP_1 (
  EMP_NUM CHAR(3) NOT NULL,
  EMP_LNAME VARCHAR(15) NOT NULL,
  EMP_FNAME VARCHAR(15) NOT NULL,
  EMP_INITIAL CHAR(1) NULL DEFAULT NULL,
  EMP_HIREDATE DATE NULL DEFAULT NULL,
  JOB_CODE CHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (EMP_NUM),
  FOREIGN KEY (JOB_CODE) REFERENCES JOB(JOB_CODE) ON UPDATE CASCADE
);
SELECT * FROM JOB;
INSERT INTO EMP_1 (EMP_NUM, EMP_FNAME, EMP_LNAME, JOB_CODE) VALUES (1, "DUC", "VO", 500);

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE FROM EMPLOYEE;

SELECT * FROM EMP_1;

DROP TABLE IF EXISTS EMP_2;
CREATE TABLE EMP_2 AS
SELECT * FROM EMP_1;


SELECT * FROM EMP_2;

ALTER TABLE EMP_2
ADD (
	EMP_PCT DECIMAL(4,2),
	PROJ_NUM CHAR(3)
);

UPDATE EMP_2
SET EMP_PCT = 5.00
WHERE EMP_NUM IN (101,105,107);



